services:
  postgres:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_pass
      POSTGRES_DB: sportsbook_dw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow:
    build: ./airflow
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://dw_user:dw_pass@postgres:5432/sportsbook_dw
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: utc
      AIRFLOW__WEBSERVER__SESSION_BACKEND: securecookie
      AIRFLOW__WEBSERVER__SECRET_KEY: this_is_a_dev_secret_key
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./great_expectations:/opt/airflow/great_expectations
      - ./data:/opt/airflow/data
      - ./dbt:/opt/airflow/dbt
      - ./profiles:/home/airflow/.dbt

    ports:
      - "8080:8080"
    command: airflow standalone

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.9
    container_name: dbt
    depends_on:
      - postgres
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    volumes:
      - ./dbt:/dbt
      - ./profiles:/root/.dbt
    working_dir: /dbt
    entrypoint: ["/bin/bash", "-c"]
    command: ["tail -f /dev/null"]

  dbt-docs-generate:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.9
    container_name: dbt_docs_generate
    depends_on:
      - postgres
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    volumes:
      - ./dbt:/dbt
      - ./profiles:/root/.dbt
    working_dir: /dbt
    entrypoint: ["dbt"]
    command: ["docs", "generate"]



  dbt-docs-ui:
    image: nginx:alpine
    container_name: dbt_docs_ui
    depends_on:
      - dbt-docs-generate
    ports:
      - "8081:80"
    volumes:
      - ./dbt/target:/usr/share/nginx/html:ro



  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: sportsbook_dw
      MB_DB_PORT: 5432
      MB_DB_USER: dw_user
      MB_DB_PASS: dw_pass
      MB_DB_HOST: postgres

volumes:
  pgdata:
